"""agregar idempotency_key a orders

Revision ID: 06ec4e3ec38b
Revises: 347e3321aecd
Create Date: 2026-09-17 19:36:08.638686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ec4e3ec38b'
down_revision = '347e3321aecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_orders_idempotency_key'), ['idempotency_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_idempotency_key'))
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
