events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth-service:5001;
    }

    upstream product_service {
        server product-service:5002;
    }

    upstream order_service {
        server order-service:5003;
    }

    server {
        listen 80;

        location /api/auth/ {
            rewrite ^/api/auth/(.*)$ /$1 break;
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/products/ {
            rewrite ^/api/products/(.*)$ /$1 break;
            proxy_pass http://product_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/orders/ {
            rewrite ^/api/orders/(.*)$ /$1 break;
            proxy_pass http://order_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
